services:
  postgres:
    image: postgres:15
    container_name: company-postgres
    environment:
      POSTGRES_DB: company_db
      POSTGRES_USER: company
      POSTGRES_PASSWORD: company123
    ports:
      - "5433:5432"
    volumes:
      - company_pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "until mc alias set local http://minio:9000 minioadmin minioadmin; do echo 'waiting for minio...'; sleep 1; done;
      mc mb -p local/products || true;"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  company-erp:
    build:
      context: ./company-erp
      dockerfile: Dockerfile
    container_name: company-erp
    depends_on:
      - postgres
      - minio
      - minio-init
      - rabbitmq
    environment:
      PORT: "3000"
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: company
      DB_PASS: company123
      DB_NAME: company_db
      TYPEORM_SYNC: "true"
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: products
      MINIO_PUBLIC_URL: http://localhost:9000
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      RABBITMQ_EXCHANGE: company.events
    ports:
      - "3001:3000"

volumes:
  company_pgdata:
  minio_data:
